version: '3.8'

networks:
  spark-network:
    driver: bridge

services:
  spark-master:
    image: bitnami/spark:3.5
    container_name: spark-master
    ports:
      - "7077:7077"
      - "8080:8080"
    networks:
      - spark-network
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ./shared-workspace:/opt/workspace
      - ./host-scripts:/opt/host-scripts
      - ./jars:/opt/spark/jar2

  spark-worker-1:
    image: bitnami/spark:3.5
    container_name: spark-worker-1
    networks:
      - spark-network
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2g
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ./shared-workspace:/opt/workspace
      - ./host-scripts:/opt/host-scripts
      - ./jars:/opt/spark/jar2
    depends_on:
      - spark-master

  spark-worker-2:
    image: bitnami/spark:3.5
    container_name: spark-worker-2
    networks:
      - spark-network
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2g
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ./shared-workspace:/opt/workspace
      - ./host-scripts:/opt/host-scripts
      - ./jars:/opt/spark/jar2
    depends_on:
      - spark-master

  spark-worker-3:
    image: bitnami/spark:3.5
    container_name: spark-worker-3
    networks:
      - spark-network
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2g
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ./shared-workspace:/opt/workspace
      - ./host-scripts:/opt/host-scripts
      - ./jars:/opt/spark/jar2
    depends_on:
      - spark-master

  spark-worker-4:
    image: bitnami/spark:3.5
    container_name: spark-worker-4
    networks:
      - spark-network
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2g
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ./shared-workspace:/opt/workspace
      - ./host-scripts:/opt/host-scripts
      - ./jars:/opt/spark/jar2
    depends_on:
      - spark-master